site_name: fastlane docs
theme: readthedocs
copyright: Copyright &copy; 2016 <a href="https://fastlane.tools">fastlane</a>
site_author: "fastlane team"
site_description: "Documentation for fastlane tools, the easiest way to automate building and releasing your iOS and Android apps"
favicon: "img/favicon.ico"
google_analytics: ["UA-18658848-13", "docs.fastlane.tools"]
# strict: true # TODO: Enable once we have the docs structure
markdown_extensions:
  - pymdownx.headeranchor

pages:
- Home: index.md
- Getting Started:
  - Apple:
    - Setup: getting-started/apple/setup.md
    - Screenshots: getting-started/apple/screenshots.md
    - Beta Deployment: getting-started/apple/beta-deployment.md
    - App Store Deployment: getting-started/apple/appstore-deployment.md
  - Android:
    - Setup: getting-started/android/setup.md
- Actions: actions/Actions.md
- FAQs: FAQs.md
- Codesigning:
  - Getting Started: codesigning/GettingStarted.md
  - Xcode Project: codesigning/XcodeProject.md
  - Troubleshooting: codesigning/Troubleshooting.md
- Plugins:
  - AvailablePlugins: plugins/AvailablePlugins.md
  - Create your own plugin: plugins/CreatePlugin.md
  - Plugins Troubleshooting: plugins/PluginsTroubleshooting.md
- Best Practices:
  - Gitignore: "best-practices/Gitignore.md"
  - Continuous Integration: "best-practices/ContinuousIntegration.md"
- Advanced: "Advanced.md"
- Contributing:
  - UI: contributing/UI.md
  - Contribution Guidelines: contributing/CONTRIBUTING.md
