site_name: fastlane docs
theme: readthedocs
site_author: "fastlane team"
site_description: "Documentation for fastlane tools, the easiest way to automate building and releasing your iOS and Android apps"
strict: true

pages:
- Home: index.md
- Getting Started: 
  - Setup: getting-started/setup.md
  - Screenshots: getting-started/screenshots.md
  - Beta Deployment: getting-started/beta-deployment.md
  - App Store Deployment: getting-started/appstore-deployment.md
- Actions: actions/Actions.md
- FAQs: FAQs.md
- Codesigning:
  - Getting Started: codesigning/GettingStarted.md
  - Xcode Project: codesigning/XcodeProject.md
  - Troubleshooting: codesigning/Troubleshooting.md
- Plugins:
  - AvailablePlugins: plugins/AvailablePlugins.md
  - Create your own plugin: plugins/CreatePlugin.md
  - Plugins Troubleshooting: plugins/PluginsTroubleshooting.md
- Best Practices: 
  - Gitignore: "best-practices/Gitignore.md"
  - Continuous Integration: "best-practices/ContinuousIntegration.md"
- Advanced: "Advanced.md"
- Contributing:
  - UI: contributing/UI.md
  - Contribution Guidelines: contributing/CONTRIBUTING.md
